#!/usr/bin/env python

import subprocess
import argparse

USERNAME = "santatra"
IP = "185.246.84.173"
REMOTE_HOME ="/home/santatra/k8s/k3d/nginx"
REMOTE_REF = f"{USERNAME}@{IP}"
REMOTE_HOME_REF = f'{REMOTE_REF}:{REMOTE_HOME}'


def test_ratsy():
    remote_nginx = "/var/ossec"
    cmd = "ssh -t {0} \"ls -lh {1}\"".format(
            REMOTE_REF,
            remote_nginx)
    subprocess.run(cmd, shell=True)
    exit(0)


def exec_on_remote(cmd, isRoot=True):
    rem_cmd = "sudo " + cmd if isRoot else cmd
    remote_cmd = "ssh -t {0} {1}".format(
            REMOTE_REF,
            rem_cmd
            )
    subprocess.run(remote_cmd, shell=True)


def safe_nginx_reload():
    cmd = "nginx -t"
    exec_on_remote(cmd, isRoot=False)


def sudo_sync(src, dest):
    # Sync file to /nginx
    cmd = "rsync -aPv {0} {1}".format(
            src,
            dest
            )
    exec_on_remote(cmd)

def sudo_fetch(fetch_default=False):
    # fetch_default: alaina koa ilay /nginx/sites-available/default
    remote_moja_file = "/etc/nginx/sites-available/mojaloop"
    cmd = "rsync -aP {0} {1}".format(
            remote_moja_file,
            REMOTE_HOME
            )
    exec_on_remote(cmd)
    if fetch_default:
        remote_fetch_default = "/etc/nginx/sites-available/default"
        cmd = "rsync -aP {0} {1}".format(
                remote_fetch_default,
                REMOTE_HOME
                )
        exec_on_remote(cmd)


def main():
    targets = "mojaloop"

    # Set parser
    parser = argparse.ArgumentParser(description="Sync {0} to remote server".format(targets))
    parser.add_argument("--debug",
                        help=f"Fanaovana test sy debug",
                        action="store_true")
    parser.add_argument("--default",
                        help=f"Ampiasaina miaraka @ --pull; alaina koa ilay nginx default file. [ Mbola experimental ]",
                        action="store_true")
    parser.add_argument("--pull",
                        help=f"Alaina ilay remote file {targets}",
                        action="store_true")
    args = parser.parse_args()

    if args.debug:
        test_ratsy()

    if args.default:
        print("Mbola en mode test ilay --default fa mbola tsy mande !")

    cmd = [ "rsync", "-Pua" ]
    if args.pull:
        sudo_fetch()
        cmd.append("{}/{}".format(REMOTE_HOME_REF, targets))
        cmd.append(".")
    else:
        cmd.append("--delete")
        cmd.append(targets)
        cmd.append(REMOTE_HOME_REF)

    subprocess.run(
            cmd,
            check=True,
            )

    nginx_dest = "/etc/nginx/sites-available"
    sudo_sync(
            "{}/mojaloop".format(REMOTE_HOME),
            nginx_dest)

if __name__ == '__main__':
    main()
